version: '1.0'
services:
  web:
    build: ./php/
    container_name: php8.2-nginx
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:8000
    volumes:
      - ./app:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: zxcv1234
      MYSQL_DATABASE: kepegawaian
      MYSQL_USER: zxcv
      MYSQL_PASSWORD: zxcv1234
    volumes:
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db